/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html'],
  theme: {
    extend: {
      colors: {
        bg: '#ffffff',
        'bg-dark': '#0f1418',
        panel: '#ffffff',
        'panel-dark': '#151a20',
        'panel-2': '#f3f6fb',
        'panel-2-dark': '#0f141a',
        text: '#0b1220',
        'text-dark': '#e6eef7',
        muted: '#5b6b7f',
        'muted-dark': '#9fb0c3',
        accent: '#2563eb',
        'accent-dark': '#5aa5ff',
        'accent-strong': '#1d4ed8',
        'accent-strong-dark': '#377df5',
        'accent-2': '#16a34a',
        'accent-2-dark': '#7bd389',
        danger: '#dc2626',
        'danger-dark': '#ff6b6b',
        border: '#e2e8f0',
        'border-dark': '#223042',
        code: '#eef2f7',
        'code-dark': '#0b0f14',
        // Chart palette (light / dark pairs where needed)
        'chart-1': '#2563eb',
        'chart-2': '#16a34a',
        'chart-3': '#9333ea',
        'chart-4': '#dc2626',
        'chart-5': '#f59e0b',
        'chart-6': '#0891b2',
        'chart-7': '#64748b',
        'chart-8': '#4f46e5',
        'chart-9': '#059669',
        'chart-10': '#d946ef',
        // Load Balance semantic colors (light mode)
        'lb-heating': '#dc2626',
        'lb-heating-dark': '#f87171',
        'lb-cooling': '#2563eb', 
        'lb-cooling-dark': '#60a5fa',
        'lb-internal': '#f59e0b',
        'lb-internal-dark': '#fbbf24',
        'lb-solar': '#ea580c',
        'lb-solar-dark': '#fb923c',
        'lb-inf-gain': '#f97316',
        'lb-inf-gain-dark': '#fdba74',
        'lb-inf-loss': '#0ea5e9',
        'lb-inf-loss-dark': '#7dd3fc',
        'lb-vent-gain': '#f43f5e',
        'lb-vent-gain-dark': '#fda4af',
        'lb-vent-loss': '#06b6d4',
        'lb-vent-loss-dark': '#67e8f9',
        'lb-cond-gain': '#7c3aed',
        'lb-cond-gain-dark': '#a78bfa',
        'lb-cond-loss': '#64748b',
        'lb-cond-loss-dark': '#94a3b8',
        'lb-storage': '#9333ea',
        'lb-storage-dark': '#c084fc',
      },
    },
  },
  plugins: [],
};
