name: Bug report
description: Report a problem or unexpected behavior
labels: [bug]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve EnergyPlus Dashboard!
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the problem. Include screenshots if helpful.
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    
      description: List the minimal steps to reproduce the issue.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: input
    id: version
    attributes:
      label: App version
      description: Shown next to the app title (click to see changelog)
      placeholder: e.g. 1.2.3
  - type: dropdown
    id: units
    attributes:
      label: Units mode
      options:
        - SI
        - IP
  - type: dropdown
    id: theme
    attributes:
      label: Theme
      options:
        - light
        - dark
  - type: input
    id: browser
    attributes:
      label: Browser and version
      placeholder: e.g. Chrome 126, Safari 17
  - type: textarea
    id: logs
    attributes:
      label: Console errors
      description: If possible, paste any errors from the browser console.
      render: shell
